/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 9
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_class_name_token1 = 1,
  sym_segment = 2,
  sym_separator = 3,
  sym__continuation_separator = 4,
  sym_source = 5,
  sym_class_name = 6,
  aux_sym_source_repeat1 = 7,
  aux_sym_class_name_repeat1 = 8,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_class_name_token1] = "segment",
  [sym_segment] = "segment",
  [sym_separator] = "separator",
  [sym__continuation_separator] = "separator",
  [sym_source] = "source",
  [sym_class_name] = "class_name",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_class_name_repeat1] = "class_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_class_name_token1] = sym_segment,
  [sym_segment] = sym_segment,
  [sym_separator] = sym_separator,
  [sym__continuation_separator] = sym_separator,
  [sym_source] = sym_source,
  [sym_class_name] = sym_class_name,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_class_name_repeat1] = aux_sym_class_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_class_name_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym__continuation_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '-' ||
          lookahead == '/' ||
          lookahead == ':') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '-' &&
          lookahead != '/' &&
          lookahead != ':') ADVANCE(4);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '-' ||
          lookahead == '/' ||
          lookahead == ':') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '-' &&
          lookahead != '/' &&
          lookahead != ':') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_segment);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '-' &&
          lookahead != '/' &&
          lookahead != ':') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '-' ||
          lookahead == '/' ||
          lookahead == ':') ADVANCE(6);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2, .external_lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2, .external_lex_state = 1},
  [5] = {.lex_state = 2, .external_lex_state = 1},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2, .external_lex_state = 1},
  [8] = {.lex_state = 2, .external_lex_state = 1},
  [9] = {.lex_state = 2, .external_lex_state = 1},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_class_name_token1] = ACTIONS(1),
    [sym_segment] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym__continuation_separator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(11),
    [sym_class_name] = STATE(3),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_segment] = ACTIONS(5),
    [sym_separator] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym_class_name_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_segment] = ACTIONS(9),
    [sym_separator] = ACTIONS(9),
    [sym__continuation_separator] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_class_name] = STATE(6),
    [aux_sym_source_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_segment] = ACTIONS(5),
    [sym_separator] = ACTIONS(7),
  },
  [STATE(4)] = {
    [aux_sym_class_name_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_segment] = ACTIONS(15),
    [sym_separator] = ACTIONS(15),
    [sym__continuation_separator] = ACTIONS(11),
  },
  [STATE(5)] = {
    [aux_sym_class_name_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_segment] = ACTIONS(15),
    [sym_separator] = ACTIONS(15),
    [sym__continuation_separator] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym_class_name] = STATE(6),
    [aux_sym_source_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_segment] = ACTIONS(19),
    [sym_separator] = ACTIONS(22),
  },
  [STATE(7)] = {
    [aux_sym_class_name_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_segment] = ACTIONS(25),
    [sym_separator] = ACTIONS(25),
    [sym__continuation_separator] = ACTIONS(27),
  },
  [STATE(8)] = {
    [aux_sym_class_name_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(30),
    [sym_segment] = ACTIONS(30),
    [sym_separator] = ACTIONS(30),
    [sym__continuation_separator] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(25), 4,
      sym__continuation_separator,
      ts_builtin_sym_end,
      sym_segment,
      sym_separator,
  [7] = 1,
    ACTIONS(32), 1,
      sym_segment,
  [11] = 1,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
  [15] = 1,
    ACTIONS(36), 1,
      aux_sym_class_name_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 7,
  [SMALL_STATE(11)] = 11,
  [SMALL_STATE(12)] = 15,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_name, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_name, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_name_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_name_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_name, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [34] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__continuation_separator = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__continuation_separator] = sym__continuation_separator,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__continuation_separator] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_class_list_external_scanner_create(void);
void tree_sitter_class_list_external_scanner_destroy(void *);
bool tree_sitter_class_list_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_class_list_external_scanner_serialize(void *, char *);
void tree_sitter_class_list_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_class_list(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_class_list_external_scanner_create,
      tree_sitter_class_list_external_scanner_destroy,
      tree_sitter_class_list_external_scanner_scan,
      tree_sitter_class_list_external_scanner_serialize,
      tree_sitter_class_list_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
