variable "project" {}
variable "region" {}
variable "credentials_file" {}
variable "namespace" {}
variable "tfe_license_name" {}
variable "tfe_license_path" {}
variable "fqdn" {}
variable "ssl_certificate_name" {}
variable "proxy_ip" {}
variable "proxy_cert_name" {}
variable "proxy_cert_path" {}
variable "network" {}
variable "subnetwork" {}
variable "dns_zone_name" {}
