# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: boundary
# Description: 

terraform {
  required_version = ">= 0.13.0, < 0.15"
  required_providers {
    boundary = {
      source  = "hashicorp/boundary"
      version = "1.0.2"
    }
  }
  backend "consul" {
    address = "localhost:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "boundary" {
  addr             = var.boundary.addr
  recovery_kms_hcl = var.boundary.recovery_kms_hcl
}

provider "http" {
}

module "boundary" {
  source   = "./boundary"
  services = var.services
}
