(script
  (expression_statement
    (heredoc
      (embedded_braced_expression
        (call_expression
          function: (call_expression
            function: (variable)
            (arguments))
          (arguments)))
      (embedded_braced_expression
        (call_expression
          function: (selection_expression
            (call_expression
              function: (variable)
              (arguments))
            (qualified_identifier
              (identifier)))
          (arguments)))
      (embedded_braced_expression
        (call_expression
          function: (subscript_expression
            (call_expression
              function: (variable)
              (arguments))
            (string))
          (arguments))))))
