(script
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (string))
  (expression_statement
    (prefixed_string
      prefix: (identifier)
      (string)))
  (expression_statement
    (prefixed_string
      prefix: (identifier)
      (string))))
