(script
  (concurrent_statement
    (compound_statement
      (expression_statement
        (await_expression
          (call_expression
            function: (qualified_identifier
              (identifier))
            (arguments))))
      (expression_statement
        (await_expression
          (call_expression
            function: (qualified_identifier
              (identifier))
            (arguments))))))
  (concurrent_statement
    (compound_statement
      (expression_statement
        (await_expression
          (call_expression
            function: (qualified_identifier
              (identifier))
            (arguments))))
      (expression_statement
        (await_expression
          (async_expression
            (compound_statement
              (expression_statement
                (await_expression
                  (call_expression
                    function: (qualified_identifier
                      (identifier))
                    (arguments)))))))))))
