(script
  (foreach_statement
    collection: (variable
      (identifier))
    value: (variable
      (identifier))
    body: (compound_statement))
  (foreach_statement
    collection: (array
      (array_type))
    key: (variable
      (identifier))
    value: (subscript_expression
      (variable
        (identifier))
      (integer))
    body: (compound_statement))
  (foreach_statement
    collection: (array
      (array_type)
      (type_arguments
        (type_specifier)
        (type_specifier)))
    value: (list_expression
      (subscript_expression
        (variable
          (identifier))
        (subscript_expression
          (as_expression
            left: (array
              (array_type))
            right: (type_specifier))
          (integer)))
      (variable
        (identifier)))
    body: (compound_statement))
  (comment)
  (comment)
  (comment))
