(script
  (if_statement
    condition: (parenthesized_expression
      (integer))
    body: (expression_statement
      (integer))
    else: (expression_statement
      (integer)))
  (if_statement
    condition: (parenthesized_expression
      (integer))
    body: (compound_statement
      (expression_statement
        (integer)))
    else: (compound_statement
      (expression_statement
        (integer)))))
