(script
  (if_statement
    this: (parenthesized_expression
      (integer))
    then: (expression_statement
      (integer))
    this: (parenthesized_expression
      (integer))
    then: (expression_statement
      (integer))
    this: (parenthesized_expression
      (integer))
    then: (expression_statement
      (integer))
    else: (expression_statement
      (integer)))
  (if_statement
    this: (parenthesized_expression
      (integer))
    then: (compound_statement)
    this: (parenthesized_expression
      (integer))
    then: (compound_statement)
    this: (parenthesized_expression
      (integer))
    then: (compound_statement)
    else: (compound_statement)))
