(script
  (if_statement
    this: (parenthesized_expression
      (integer))
    then: (if_statement
      this: (parenthesized_expression
        (integer))
      then: (expression_statement
        (integer))
      else: (expression_statement
        (integer))))
  (if_statement
    this: (parenthesized_expression
      (integer))
    then: (compound_statement
      (if_statement
        this: (parenthesized_expression
          (integer))
        then: (expression_statement
          (integer))))
    else: (compound_statement
      (if_statement
        this: (parenthesized_expression
          (integer))
        then: (compound_statement
          (expression_statement
            (integer)))))))
