(script
  (using_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (new_expression
        (qualified_identifier
          (identifier))
        (arguments)))
    (binary_expression
      left: (variable
        (identifier))
      right: (new_expression
        (qualified_identifier
          (identifier))
        (arguments
          (argument
            (string))
          (argument
            (string)))))
    (compound_statement)))
