fun v() {
    SendPayGasSeparately;
    // <- constant.builtin

    SendIgnoreErrors;
    // <- constant.builtin

    SendDestroyIfZero;
    // <- constant.builtin

    SendRemainingValue;
    // <- constant.builtin

    SendRemainingBalance;
    // <- constant.builtin

    ReserveExact;
    // <- constant.builtin

    ReserveAllExcept;
    // <- constant.builtin

    ReserveAtMost;
    // <- constant.builtin

    ReserveAddOriginalBalance;
    // <- constant.builtin

    ReserveInvertSign;
    // <- constant.builtin

    ReserveBounceIfActionFail;
    // <- constant.builtin

    SendParameters{};
    // <- type.builtin
}
