fun fun() {
// <- keyword
//  ^ function
    abs();
    // <- function.builtin
    beginCell();
    // <- function.builtin
    beginComment();
    // <- function.builtin
    beginString();
    // <- function.builtin
    beginStringFromBuilder();
    // <- function.builtin
    beginTailString();
    // <- function.builtin
    cell();
    // <- function.builtin
    checkDataSignature();
    // <- function.builtin
    checkSignature();
    // <- function.builtin
    contractAddress();
    // <- function.builtin
    contractAddressExt();
    // <- function.builtin
    dump();
    // <- function.builtin
    dumpStack();
    // <- function.builtin
    emit();
    // <- function.builtin
    emptyCell();
    // <- function.builtin
    getConfigParam();
    // <- function.builtin
    log();
    // <- function.builtin
    log2();
    // <- function.builtin
    max();
    // <- function.builtin
    min();
    // <- function.builtin
    myAddress();
    // <- function.builtin
    myBalance();
    // <- function.builtin
    nativePrepareRandom();
    // <- function.builtin
    nativeRandom();
    // <- function.builtin
    nativeRandomInterval();
    // <- function.builtin
    nativeRandomize();
    // <- function.builtin
    nativeRandomizeLt();
    // <- function.builtin
    nativeReserve();
    // <- function.builtin
    nativeThrowUnless();
    // <- function.builtin
    nativeThrowIf();
    // <- function.builtin
    newAddress();
    // <- function.builtin
    now();
    // <- function.builtin
    pow();
    // <- function.builtin
    pow2();
    // <- function.builtin
    random();
    // <- function.builtin
    randomInt();
    // <- function.builtin
    require();
    // <- function.builtin
    send();
    // <- function.builtin
    sender();
    // <- function.builtin
    sha256();
    // <- function.builtin
    throw();
    // <- function.builtin
    ton();
    // <- function.builtin
}
