#! /usr/bin/env dshell

import 'dart:io';
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create test.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main(List<String> args) {
  if (args.length < 1) {
    print("Usage: dart test.dart /path/to/directory/for/testing");
  }
  final files = [];
  find('*.dart', root: args[0], includeHidden: false).forEach((file) {
    files.add(file);
  });
  var lines = 0;
  final sectionSize = 100;
  final maxPrint = 300;
  var linesPrinted = 0;
  var errorLines = 0;
  for (var i = 0; i < files.length; i += sectionSize) {
    final result = Process.runSync('tree-sitter', [
      'parse',
      ...files.sublist(
          i, i + sectionSize < files.length ? i + sectionSize : files.length)
    ]);
    for (final line in result.stdout.split('\n')) {
      lines++;
      if (line.contains('ERROR')) {
        errorLines++;
        if (linesPrinted < maxPrint) {
          linesPrinted++;
          print(line);
        }
      }
    }
  }
  print('Processed $lines lines of tree-sitter output');
  print('Error lines $errorLines');
  print('Error percentage ${errorLines * 100 / lines}%');
}
