# This is a TOML document

title = "TOML Example Changed"

[owner]
name = "Tom Preston-Werner"
dob = 2000-01-31T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"

str1 = """
Roses are red
Violets are blue"""
