(script
  (function_declaration
    (async_modifier)
    name: (identifier)
    parameters: (parameters)
    return_type: (primitive_type)
    body: (compound_statement))
  (function_declaration
    (async_modifier)
    name: (identifier)
    type_parameters: (type_parameters
      (type_parameter
        name: (identifier)
        type_constraint: (subtype_constraint
          (primitive_type))))
    parameters: (parameters)
    body: (compound_statement))
  (expression_statement
    (lambda_expression
      (async_modifier)
      parameters: (parameters
        (parameter
          name: (variable
            (identifier))))
      body: (binary_expression
        left: (variable
          (identifier))
        right: (integer)))))
