(script
  (function_declaration
    (async_modifier)
    name: (identifier)
    (parameters)
    return_type: (primitive_type)
    body: (compound_statement))
  (function_declaration
    (async_modifier)
    name: (identifier)
    (type_parameters
      (type_parameter
        name: (identifier)
        as: (primitive_type)))
    (parameters)
    body: (compound_statement))
  (expression_statement
    (lambda_expression
      (async_modifier)
      (parameters
        (parameter
          name: (variable
            (identifier))))
      body: (binary_expression
        left: (variable
          (identifier))
        right: (integer)))))
