(script
  (class_declaration
    (abstract_modifier)
    (final_modifier)
    name: (identifier)
    (type_parameters
      (type_parameter
        name: (identifier)
        as: (type_identifier
          (identifier)))
      (type_parameter
        name: (identifier)
        super: (generic_type
          (type_identifier
            (identifier))
          (type_arguments
            (type_identifier
              (identifier))
            (type_identifier
              (identifier))))))
    (extends_clause
      (type_identifier
        (identifier)))
    (implements_clause
      (generic_type
        (type_identifier
          (identifier)
          (identifier))
        (type_arguments
          (type_identifier
            (identifier))
          (type_identifier
            (identifier))))
      (type_identifier
        (identifier)
        (identifier)))
    body: (class_body
      (method_declaration
        name: (identifier)
        (type_parameters
          (type_parameter
            name: (identifier)
            as: (type_identifier
              (identifier)))
          (type_parameter
            name: (identifier)
            super: (type_identifier
              (identifier))))
        (parameters)
        return_type: (type_identifier
          (identifier))
        body: (compound_statement)))))
