(script
  (class_declaration
    (abstract_modifier)
    (final_modifier)
    name: (identifier)
    (extends_clause
      (type_specifier
        (qualified_identifier
          (identifier))))
    (implements_clause
      (type_specifier
        (qualified_identifier
          (identifier)
          (identifier)))
      (type_specifier
        (qualified_identifier
          (identifier))))
    body: (member_declarations
      (method_declaration
        name: (identifier)
        (parameters)
        body: (compound_statement))
      (method_declaration
        (final_modifier)
        name: (identifier)
        (parameters)
        return_type: (type_specifier)
        body: (compound_statement))
      (method_declaration
        (abstract_modifier)
        name: (identifier)
        (parameters))
      (method_declaration
        (abstract_modifier)
        name: (identifier)
        (parameters)
        return_type: (type_specifier)))))
