(script
  (class_declaration
    name: (identifier)
    body: (class_body))
  (interface_declaration
    name: (identifier)
    body: (class_body))
  (trait_declaration
    name: (identifier)
    body: (class_body))
  (interface_declaration
    name: (identifier)
    (extends_clause
      (type_identifier
        (identifier))
      (type_identifier
        (identifier)))
    body: (class_body))
  (trait_declaration
    name: (identifier)
    (implements_clause
      (type_identifier
        (identifier)))
    body: (class_body))
  (class_declaration
    (abstract_modifier)
    (final_modifier)
    name: (identifier)
    (extends_clause
      (type_identifier
        (identifier)))
    (implements_clause
      (type_identifier
        (identifier)
        (identifier))
      (type_identifier
        (identifier)))
    body: (class_body
      (method_declaration
        name: (identifier)
        (parameters)
        body: (compound_statement))
      (method_declaration
        (final_modifier)
        name: (identifier)
        (parameters)
        return_type: (primitive_type)
        body: (compound_statement))
      (method_declaration
        (abstract_modifier)
        name: (identifier)
        (parameters))
      (method_declaration
        (abstract_modifier)
        name: (identifier)
        (parameters)
        return_type: (primitive_type)))))
