(script
  (const_declaration
    type: (primitive_type)
    (const_declarator
      name: (identifier)
      value: (integer)))
  (const_declaration
    type: (primitive_type)
    (const_declarator
      name: (identifier)
      value: (integer))
    (const_declarator
      name: (identifier)
      value: (integer)))
  (const_declaration
    (const_declarator
      name: (identifier)
      value: (integer)))
  (const_declaration
    (const_declarator
      name: (identifier)
      value: (integer))
    (const_declarator
      name: (identifier)
      value: (integer))))
