(script
  (enum_declaration
    name: (identifier)
    type: (type_specifier))
  (enum_declaration
    (attribute_modifier
      (qualified_identifier
        (identifier)))
    name: (identifier)
    type: (type_specifier)
    (field_specifier
      (identifier)
      (integer))
    (field_specifier
      (identifier)
      (integer))
    (field_specifier
      (identifier)
      (scoped_identifier
        (qualified_identifier
          (identifier))
        (identifier)))
    (field_specifier
      (identifier)
      (binary_expression
        left: (string)
        right: (string)))))
