(script
  (function_declaration
    name: (identifier)
    (parameters
      (parameter
        (attribute_modifier
          (qualified_identifier
            (identifier)))
        (inout_modifier)
        type: (type_specifier)
        name: (variable
          (identifier)))
      (parameter
        (inout_modifier)
        type: (type_specifier)
        name: (variable
          (identifier))))
    body: (compound_statement)))
