(script
  (function_declaration
    name: (identifier)
    (parameters)
    return_type: (primitive_type)
    body: (compound_statement))
  (function_declaration
    name: (identifier)
    (parameters)
    body: (compound_statement))
  (function_declaration
    name: (identifier)
    (parameters
      (parameter
        name: (variable
          (identifier))))
    body: (compound_statement))
  (function_declaration
    name: (identifier)
    (parameters
      (parameter
        type: (primitive_type)
        name: (variable
          (identifier))))
    body: (compound_statement))
  (function_declaration
    name: (identifier)
    (parameters
      (parameter
        type: (primitive_type)
        name: (variable
          (identifier))))
    return_type: (primitive_type)
    body: (compound_statement))
  (function_declaration
    name: (identifier)
    (parameters
      (parameter
        type: (primitive_type)
        name: (variable
          (identifier)))
      (parameter
        type: (primitive_type)
        name: (variable
          (identifier))))
    return_type: (primitive_type)
    body: (compound_statement)))
