(script
  (class_declaration
    (abstract_modifier)
    name: (identifier)
    body: (class_body
      (method_declaration
        (static_modifier)
        name: (identifier)
        (parameters)
        return_type: (primitive_type)
        body: (compound_statement))
      (method_declaration
        (visibility_modifier)
        name: (identifier)
        (parameters)
        return_type: (primitive_type)
        body: (compound_statement))
      (method_declaration
        name: (identifier)
        (parameters)
        return_type: (primitive_type)
        body: (compound_statement))
      (method_declaration
        (abstract_modifier)
        (visibility_modifier)
        (static_modifier)
        name: (identifier)
        (parameters))
      (method_declaration
        (final_modifier)
        (visibility_modifier)
        (static_modifier)
        name: (identifier)
        (parameters)
        return_type: (primitive_type)
        body: (compound_statement)))))
