(script
  (class_declaration
    name: (identifier)
    body: (member_declarations
      (type_const_declaration
        name: (identifier))
      (type_const_declaration
        name: (identifier)
        type: (type_specifier))
      (type_const_declaration
        name: (identifier)
        as: (type_specifier))
      (type_const_declaration
        name: (identifier)
        as: (type_specifier)
        type: (type_specifier))
      (type_const_declaration
        (abstract_modifier)
        name: (identifier)
        as: (type_specifier
          (nullable_modifier))
        type: (type_specifier
          (nullable_modifier))))))
