(script
  (expression_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (anonymous_function_expression
        (parameters
          (parameter
            name: (variable
              (identifier))))
        body: (compound_statement))))
  (expression_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (anonymous_function_expression
        (parameters
          (parameter
            name: (variable
              (identifier)))
          (parameter
            name: (variable
              (identifier))))
        return_type: (type_specifier)
        body: (compound_statement)))))
