(script
  (expression_statement
    (cast_expression
      value: (string)))
  (expression_statement
    (cast_expression
      value: (string)))
  (expression_statement
    (cast_expression
      value: (string)))
  (expression_statement
    (cast_expression
      value: (string)))
  (comment)
  (expression_statement
    (cast_expression
      value: (prefix_unary_expression
        operand: (string)))))
