(script
  (expression_statement
    (function_call_expression
      function: (qualified_identifier
        (identifier))
      (arguments)))
  (expression_statement
    (function_call_expression
      function: (qualified_identifier
        (identifier))
      function: (type_arguments
        (primitive_type))
      (arguments
        (argument
          (integer))
        (argument
          (inout_modifier)
          (variable
            (identifier)))
        (argument
          (variadic_modifier)
          (null)))))
  (expression_statement
    (function_call_expression
      function: (subscript_expression
        (variable
          (identifier))
        (function_call_expression
          function: (qualified_identifier
            (identifier))
          (arguments)))
      (arguments))))
