(script
  (comment)
  (expression_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (lambda_expression
        (parameters
          (parameter
            name: (variable
              (identifier))))
        body: (call_expression
          function: (awaitable_expression
            (compound_statement
              (return_statement
                (variable
                  (identifier)))))
          (arguments
            (argument
              (integer))
            (argument
              (variadic_modifier)
              (array
                (array_type)
                (integer)
                (integer)
                (integer))))))))
  (comment)
  (expression_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (call_expression
        function: (lambda_expression
          (async_modifier)
          (parameters
            (parameter
              name: (variable
                (identifier))))
          body: (compound_statement
            (return_statement
              (variable
                (identifier)))))
        (arguments
          (argument
            (integer))
          (argument
            (variadic_modifier)
            (array
              (array_type)
              (integer)
              (integer)
              (integer)))))))
  (expression_statement
    (call_expression
      function: (parenthesized_expression
        (lambda_expression
          (parameters
            (parameter
              name: (variable
                (identifier))))
          body: (variable
            (identifier))))
      (arguments
        (argument
          (call_expression
            function: (qualified_identifier
              (identifier))
            (arguments)))
        (argument
          (inout_modifier)
          (variable
            (identifier)))))))
