(script
  (expression_statement
    (function_call_expression
      function: (scoped_identifier
        (qualified_identifier
          (identifier))
        (variable
          (identifier)))
      (arguments)))
  (expression_statement
    (function_call_expression
      function: (scoped_identifier
        (qualified_identifier
          (identifier))
        (identifier))
      (arguments))))
