(script
  (expression_statement
    (ternary_expression
      condition: (binary_expression
        left: (selection_expression
          (variable)
          (safe_modifier)
          (variable))
        right: (selection_expression
          (variable)
          (safe_modifier)
          (variable)))
      consequence: (selection_expression
        (variable)
        (safe_modifier)
        (variable))
      alternative: (selection_expression
        (variable)
        (safe_modifier)
        (variable))))
  (expression_statement
    (ternary_expression
      condition: (binary_expression
        left: (subscript_expression
          (selection_expression
            (subscript_expression
              (variable)
              (selection_expression
                (variable)
                (safe_modifier)
                (variable)))
            (safe_modifier)
            (variable))
          (selection_expression
            (variable)
            (safe_modifier)
            (variable)))
        right: (subscript_expression
          (selection_expression
            (subscript_expression
              (variable)
              (selection_expression
                (variable)
                (safe_modifier)
                (variable)))
            (safe_modifier)
            (variable))
          (selection_expression
            (variable)
            (safe_modifier)
            (variable))))
      consequence: (subscript_expression
        (selection_expression
          (subscript_expression
            (variable)
            (selection_expression
              (variable)
              (safe_modifier)
              (variable)))
          (safe_modifier)
          (variable))
        (selection_expression
          (variable)
          (safe_modifier)
          (variable)))
      alternative: (subscript_expression
        (selection_expression
          (subscript_expression
            (variable)
            (selection_expression
              (variable)
              (safe_modifier)
              (variable)))
          (safe_modifier)
          (variable))
        (selection_expression
          (variable)
          (safe_modifier)
          (variable))))))
