(script
  (expression_statement
    (selection_expression
      (variable
        (identifier))
      name: (variable
        (identifier))))
  (expression_statement
    (selection_expression
      (qualified_identifier
        (identifier))
      name: (variable
        (identifier))))
  (expression_statement
    (selection_expression
      (qualified_identifier
        (identifier))
      name: (qualified_identifier
        (identifier))))
  (expression_statement
    (selection_expression
      (subscript_expression
        (selection_expression
          (qualified_identifier
            (identifier)
            (identifier))
          name: (variable
            (identifier)))
        (integer))
      name: (qualified_identifier
        (identifier))))
  (expression_statement
    (subscript_expression
      (selection_expression
        (subscript_expression
          (variable
            (identifier))
          (integer))
        name: (variable
          (identifier)))
      (integer)))
  (expression_statement
    (subscript_expression
      (selection_expression
        (subscript_expression
          (variable
            (identifier))
          (integer))
        name: (qualified_identifier
          (identifier)))
      (integer))))
