(script
  (expression_statement
    (ternary_expression
      condition: (variable
        (identifier))
      consequence: (true)
      alternative: (false)))
  (expression_statement
    (binary_expression
      left: (variable
        (identifier))
      right: (false)))
  (expression_statement
    (ternary_expression
      condition: (ternary_expression
        condition: (binary_expression
          left: (variable
            (identifier))
          right: (integer))
        consequence: (binary_expression
          left: (variable
            (identifier))
          right: (integer))
        alternative: (binary_expression
          left: (variable
            (identifier))
          right: (integer)))
      consequence: (integer)
      alternative: (integer)))
  (expression_statement
    (ternary_expression
      condition: (binary_expression
        left: (binary_expression
          left: (variable
            (identifier))
          right: (integer))
        right: (binary_expression
          left: (variable
            (identifier))
          right: (integer)))
      consequence: (integer)
      alternative: (integer))))
