(script
  (expression_statement
    (unary_expression
      operand: (integer)))
  (expression_statement
    (unary_expression
      operand: (integer)))
  (expression_statement
    (unary_expression
      operand: (integer)))
  (expression_statement
    (unary_expression
      operand: (integer)))
  (expression_statement
    (unary_expression
      operand: (unary_expression
        operand: (unary_expression
          operand: (unary_expression
            operand: (integer)))))))
