(script
  (expression_statement
    (prefix_unary_expression
      operand: (variable
        (identifier))))
  (expression_statement
    (prefix_unary_expression
      operand: (variable
        (identifier))))
  (expression_statement
    (postfix_unary_expression
      (variable
        (identifier))))
  (expression_statement
    (postfix_unary_expression
      (variable
        (identifier)))))
