(script
  (expression_statement
    (selection_expression
      (scoped_identifier
        (qualified_identifier
          (identifier))
        (identifier))
      (safe_modifier)
      (qualified_identifier
        (identifier))))
  (expression_statement
    (selection_expression
      (parenthesized_expression
        (binary_expression
          left: (variable
            (identifier))
          right: (variable
            (identifier))))
      (safe_modifier)
      (qualified_identifier
        (identifier))))
  (expression_statement
    (selection_expression
      (call_expression
        function: (variable
          (identifier))
        (arguments))
      (safe_modifier)
      (qualified_identifier
        (identifier)))))
