#!/bin/bash

GOROOT=$(go env GOROOT)
GO_FILES=$(find ${GOROOT}/src -name '*.go' | grep -v testdata)

PENDING_FILES=(
  'internal/big/arith.go'
)

contains-match () {
  local element
  for element in "${@:2}"; do
    if [[ "$1" =~ "$element" ]]; then
      return 0;
    fi
  done
  return 1
}

for go_file in $GO_FILES; do
  echo $go_file

  if contains-match $go_file $BAD_FILES[@]; then
    echo "PENDING"
    continue
  fi

  tree-sitter parse $go_file --quiet --time || exit 1
done
