[book]
authors = ["Wilfred Hughes"]
language = "en"
multilingual = false
src = "src"
title = "Difftastic Manual"
description = "The official manual for difftastic, the syntactic differ"

[output.html.redirect]
"/getting_started.html" = "./installation.html"
