public class Me {
// <- keyword
//     ^ keyword
//           ^ class
//              ^ punctuation
   public enum Season {WINTER, SPRING, SUMMER, FALL}
// ^ keyword
//        ^ keyword
//             ^ enum
//                    ^ punctuation
//                     ^ enumMember
//                           ^ punctuation
//                             ^ enumMember
//                                   ^ punctuation
//                                     ^ enumMember
//                                           ^ punctuation
//                                             ^ enumMember
//                                                 ^ punctuation
  {
//^ punctuation
    Season s = Season.SPRING;
//  ^ type
//         ^ variable
//           ^ operator
//             ^ enum
//                   ^ punctuation
//                    ^ enumMember
//                          ^ punctuation


  }
//^ punctuation
}
// <- punctuation