#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  anon_sym_function = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_LT_DASH = 8,
  anon_sym_LT_LT_DASH = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  anon_sym_BANG = 14,
  anon_sym_STAR = 15,
  anon_sym_EQ_EQ = 16,
  sym_identifier = 17,
  sym_integer = 18,
  anon_sym_POUND = 19,
  aux_sym_comment_token1 = 20,
  anon_sym_DQUOTE = 21,
  aux_sym_string_token1 = 22,
  anon_sym_BSLASH = 23,
  anon_sym_SQUOTE = 24,
  aux_sym_string_token2 = 25,
  sym_program = 26,
  sym_function_definition = 27,
  sym__parameter = 28,
  sym_argument_list = 29,
  sym_call = 30,
  sym_left_assignment = 31,
  sym_brace_list = 32,
  sym_subset = 33,
  sym_unary = 34,
  sym_binary = 35,
  sym__expression = 36,
  sym_comment = 37,
  sym_string = 38,
  aux_sym_program_repeat1 = 39,
  aux_sym_function_definition_repeat1 = 40,
  aux_sym_argument_list_repeat1 = 41,
  aux_sym_string_repeat1 = 42,
  aux_sym_string_repeat2 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LT_LT_DASH] = "<<-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_EQ_EQ] = "==",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_program] = "program",
  [sym_function_definition] = "function_definition",
  [sym__parameter] = "_parameter",
  [sym_argument_list] = "argument_list",
  [sym_call] = "call",
  [sym_left_assignment] = "left_assignment",
  [sym_brace_list] = "brace_list",
  [sym_subset] = "subset",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym__expression] = "_expression",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LT_LT_DASH] = anon_sym_LT_LT_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_program] = sym_program,
  [sym_function_definition] = sym_function_definition,
  [sym__parameter] = sym__parameter,
  [sym_argument_list] = sym_argument_list,
  [sym_call] = sym_call,
  [sym_left_assignment] = sym_left_assignment,
  [sym_brace_list] = sym_brace_list,
  [sym_subset] = sym_subset,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym__expression] = sym__expression,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter] = {
    .visible = false,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_left_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_list] = {
    .visible = true,
    .named = true,
  },
  [sym_subset] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(31);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(40);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_LT_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(49);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {(TSStateId)(-1)},
  [108] = {.lex_state = 37},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LT_LT_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(104),
    [sym_function_definition] = STATE(34),
    [sym_call] = STATE(34),
    [sym_left_assignment] = STATE(34),
    [sym_brace_list] = STATE(34),
    [sym_subset] = STATE(34),
    [sym_unary] = STATE(34),
    [sym_binary] = STATE(34),
    [sym__expression] = STATE(72),
    [sym_comment] = STATE(1),
    [sym_string] = STATE(34),
    [aux_sym_program_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_integer] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
  },
  [2] = {
    [sym_function_definition] = STATE(29),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(2),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(2),
    [anon_sym_function] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(24),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(32),
    [anon_sym_PLUS] = ACTIONS(32),
    [anon_sym_BANG] = ACTIONS(32),
    [sym_identifier] = ACTIONS(35),
    [sym_integer] = ACTIONS(38),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(44),
  },
  [3] = {
    [sym_function_definition] = STATE(29),
    [sym_argument_list] = STATE(102),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(3),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(4),
    [anon_sym_function] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_integer] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
  },
  [4] = {
    [sym_function_definition] = STATE(29),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(4),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(2),
    [anon_sym_function] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_integer] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
  },
  [5] = {
    [sym_function_definition] = STATE(29),
    [sym_argument_list] = STATE(100),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(5),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(4),
    [anon_sym_function] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_integer] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
  },
  [6] = {
    [sym_function_definition] = STATE(29),
    [sym_argument_list] = STATE(103),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(6),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(4),
    [anon_sym_function] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_integer] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
  },
  [7] = {
    [sym_function_definition] = STATE(29),
    [sym_argument_list] = STATE(101),
    [sym_call] = STATE(29),
    [sym_left_assignment] = STATE(29),
    [sym_brace_list] = STATE(29),
    [sym_subset] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym__expression] = STATE(42),
    [sym_comment] = STATE(7),
    [sym_string] = STATE(29),
    [aux_sym_argument_list_repeat1] = STATE(4),
    [anon_sym_function] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [sym_integer] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(63),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(8), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(69), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(71), 14,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [35] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_comment,
    ACTIONS(77), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(79), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [66] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym_comment,
    ACTIONS(81), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(83), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [97] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_program_repeat1,
    STATE(72), 1,
      sym__expression,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [146] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(12), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(89), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [177] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(93), 14,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [212] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 14,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [247] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_program_repeat1,
    STATE(71), 1,
      sym__expression,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [296] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [327] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [360] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_EQ_EQ,
    STATE(18), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(101), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(109), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(105), 9,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [405] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(115), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(117), 14,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [440] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(121), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [471] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(125), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [502] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_program_repeat1,
    STATE(22), 1,
      sym_comment,
    STATE(71), 1,
      sym__expression,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [551] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(129), 1,
      anon_sym_function,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(143), 1,
      sym_integer,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(149), 1,
      anon_sym_SQUOTE,
    STATE(71), 1,
      sym__expression,
    STATE(23), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(137), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [598] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(154), 14,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [633] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(158), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [664] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(162), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [695] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(164), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(166), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [726] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(168), 1,
      anon_sym_function,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(180), 1,
      sym_integer,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
    STATE(72), 1,
      sym__expression,
    STATE(28), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(174), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [773] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(191), 17,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [804] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_comment,
    STATE(31), 1,
      aux_sym_program_repeat1,
    STATE(71), 1,
      sym__expression,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [853] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_program_repeat1,
    STATE(31), 1,
      sym_comment,
    STATE(71), 1,
      sym__expression,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [902] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(81), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(83), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [932] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(69), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [966] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(34), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(191), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [996] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(35), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(125), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1026] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(121), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1056] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(164), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(166), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1086] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(38), 1,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(162), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1116] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(158), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1146] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(40), 1,
      sym_comment,
    ACTIONS(77), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(79), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1176] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(152), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(154), 13,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1210] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_EQ_EQ,
    STATE(42), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(201), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(203), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1254] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    ACTIONS(207), 1,
      anon_sym_EQ,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_EQ_EQ,
    STATE(43), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(209), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1298] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_EQ_EQ,
    STATE(44), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(215), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(27), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1342] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1374] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(46), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1404] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(47), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(95), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1438] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(48), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(93), 13,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1472] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(89), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1502] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(115), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(117), 13,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1536] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(17), 1,
      sym__expression,
    STATE(51), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1579] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(19), 1,
      sym__expression,
    STATE(52), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1622] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(38), 1,
      sym__expression,
    STATE(53), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1665] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      sym_comment,
    STATE(73), 1,
      sym__expression,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1708] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(26), 1,
      sym__expression,
    STATE(55), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1751] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(50), 1,
      sym__expression,
    STATE(56), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1794] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(24), 1,
      sym__expression,
    STATE(57), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1837] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(14), 1,
      sym__expression,
    STATE(58), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1880] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym__expression,
    STATE(59), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1923] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(16), 1,
      sym__expression,
    STATE(60), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1966] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(8), 1,
      sym__expression,
    STATE(61), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2009] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(45), 1,
      sym__expression,
    STATE(62), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2052] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(41), 1,
      sym__expression,
    STATE(63), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2095] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      sym__expression,
    STATE(64), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2138] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(13), 1,
      sym__expression,
    STATE(65), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2181] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(43), 1,
      sym__expression,
    STATE(66), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2224] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(48), 1,
      sym__expression,
    STATE(67), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2267] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(47), 1,
      sym__expression,
    STATE(68), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2310] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym__expression,
    STATE(69), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(34), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2353] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_function,
    ACTIONS(53), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(59), 1,
      sym_integer,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      sym__expression,
    STATE(70), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(29), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2396] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_EQ_EQ,
    STATE(71), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(217), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(219), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2438] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    ACTIONS(207), 1,
      anon_sym_EQ,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_EQ_EQ,
    STATE(72), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(209), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(217), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(219), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [2480] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(199), 1,
      anon_sym_STAR,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    ACTIONS(207), 1,
      anon_sym_EQ,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(213), 1,
      anon_sym_EQ_EQ,
    STATE(73), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(209), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(221), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2514] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(225), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      sym_comment,
    STATE(78), 1,
      aux_sym_string_repeat1,
    ACTIONS(227), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2531] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    STATE(75), 1,
      sym_comment,
    STATE(77), 1,
      aux_sym_string_repeat2,
    ACTIONS(229), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2548] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(233), 1,
      anon_sym_SQUOTE,
    STATE(76), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym_string_repeat2,
    ACTIONS(229), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2565] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    STATE(77), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym_string_repeat2,
    ACTIONS(229), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2582] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(233), 1,
      anon_sym_DQUOTE,
    STATE(78), 1,
      sym_comment,
    STATE(80), 1,
      aux_sym_string_repeat1,
    ACTIONS(227), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2599] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      sym_comment,
    STATE(80), 1,
      aux_sym_string_repeat1,
    ACTIONS(227), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2616] = 4,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(237), 1,
      anon_sym_DQUOTE,
    ACTIONS(239), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
    STATE(80), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [2631] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(225), 1,
      anon_sym_SQUOTE,
    STATE(76), 1,
      aux_sym_string_repeat2,
    STATE(81), 1,
      sym_comment,
    ACTIONS(229), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2648] = 5,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    STATE(79), 1,
      aux_sym_string_repeat1,
    STATE(82), 1,
      sym_comment,
    ACTIONS(227), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2665] = 4,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    ACTIONS(242), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
    STATE(83), 2,
      sym_comment,
      aux_sym_string_repeat2,
  [2680] = 3,
    ACTIONS(223), 1,
      anon_sym_POUND,
    STATE(84), 1,
      sym_comment,
    ACTIONS(247), 3,
      anon_sym_BSLASH,
      anon_sym_SQUOTE,
      aux_sym_string_token2,
  [2692] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(85), 1,
      sym_comment,
    STATE(95), 1,
      sym__parameter,
  [2708] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2724] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(87), 2,
      sym_comment,
      aux_sym_function_definition_repeat1,
  [2738] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2754] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_function_definition_repeat1,
    STATE(89), 1,
      sym_comment,
  [2770] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2786] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_function_definition_repeat1,
    STATE(91), 1,
      sym_comment,
  [2802] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2818] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym_function_definition_repeat1,
    STATE(93), 1,
      sym_comment,
  [2834] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(276), 1,
      anon_sym_EQ,
    STATE(94), 1,
      sym_comment,
    ACTIONS(274), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2848] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_function_definition_repeat1,
    STATE(95), 1,
      sym_comment,
  [2864] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym__parameter,
    STATE(96), 1,
      sym_comment,
  [2880] = 3,
    ACTIONS(223), 1,
      anon_sym_POUND,
    STATE(97), 1,
      sym_comment,
    ACTIONS(284), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2892] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(98), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2903] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(98), 1,
      sym__parameter,
    STATE(99), 1,
      sym_comment,
  [2916] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      sym_comment,
  [2926] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(288), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      sym_comment,
  [2936] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      sym_comment,
  [2946] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(103), 1,
      sym_comment,
  [2956] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
    STATE(104), 1,
      sym_comment,
  [2966] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(296), 1,
      anon_sym_LPAREN,
    STATE(105), 1,
      sym_comment,
  [2976] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(298), 1,
      anon_sym_LPAREN,
    STATE(106), 1,
      sym_comment,
  [2986] = 1,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [2990] = 1,
    ACTIONS(302), 1,
      aux_sym_comment_token1,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 35,
  [SMALL_STATE(10)] = 66,
  [SMALL_STATE(11)] = 97,
  [SMALL_STATE(12)] = 146,
  [SMALL_STATE(13)] = 177,
  [SMALL_STATE(14)] = 212,
  [SMALL_STATE(15)] = 247,
  [SMALL_STATE(16)] = 296,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 360,
  [SMALL_STATE(19)] = 405,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 471,
  [SMALL_STATE(22)] = 502,
  [SMALL_STATE(23)] = 551,
  [SMALL_STATE(24)] = 598,
  [SMALL_STATE(25)] = 633,
  [SMALL_STATE(26)] = 664,
  [SMALL_STATE(27)] = 695,
  [SMALL_STATE(28)] = 726,
  [SMALL_STATE(29)] = 773,
  [SMALL_STATE(30)] = 804,
  [SMALL_STATE(31)] = 853,
  [SMALL_STATE(32)] = 902,
  [SMALL_STATE(33)] = 932,
  [SMALL_STATE(34)] = 966,
  [SMALL_STATE(35)] = 996,
  [SMALL_STATE(36)] = 1026,
  [SMALL_STATE(37)] = 1056,
  [SMALL_STATE(38)] = 1086,
  [SMALL_STATE(39)] = 1116,
  [SMALL_STATE(40)] = 1146,
  [SMALL_STATE(41)] = 1176,
  [SMALL_STATE(42)] = 1210,
  [SMALL_STATE(43)] = 1254,
  [SMALL_STATE(44)] = 1298,
  [SMALL_STATE(45)] = 1342,
  [SMALL_STATE(46)] = 1374,
  [SMALL_STATE(47)] = 1404,
  [SMALL_STATE(48)] = 1438,
  [SMALL_STATE(49)] = 1472,
  [SMALL_STATE(50)] = 1502,
  [SMALL_STATE(51)] = 1536,
  [SMALL_STATE(52)] = 1579,
  [SMALL_STATE(53)] = 1622,
  [SMALL_STATE(54)] = 1665,
  [SMALL_STATE(55)] = 1708,
  [SMALL_STATE(56)] = 1751,
  [SMALL_STATE(57)] = 1794,
  [SMALL_STATE(58)] = 1837,
  [SMALL_STATE(59)] = 1880,
  [SMALL_STATE(60)] = 1923,
  [SMALL_STATE(61)] = 1966,
  [SMALL_STATE(62)] = 2009,
  [SMALL_STATE(63)] = 2052,
  [SMALL_STATE(64)] = 2095,
  [SMALL_STATE(65)] = 2138,
  [SMALL_STATE(66)] = 2181,
  [SMALL_STATE(67)] = 2224,
  [SMALL_STATE(68)] = 2267,
  [SMALL_STATE(69)] = 2310,
  [SMALL_STATE(70)] = 2353,
  [SMALL_STATE(71)] = 2396,
  [SMALL_STATE(72)] = 2438,
  [SMALL_STATE(73)] = 2480,
  [SMALL_STATE(74)] = 2514,
  [SMALL_STATE(75)] = 2531,
  [SMALL_STATE(76)] = 2548,
  [SMALL_STATE(77)] = 2565,
  [SMALL_STATE(78)] = 2582,
  [SMALL_STATE(79)] = 2599,
  [SMALL_STATE(80)] = 2616,
  [SMALL_STATE(81)] = 2631,
  [SMALL_STATE(82)] = 2648,
  [SMALL_STATE(83)] = 2665,
  [SMALL_STATE(84)] = 2680,
  [SMALL_STATE(85)] = 2692,
  [SMALL_STATE(86)] = 2708,
  [SMALL_STATE(87)] = 2724,
  [SMALL_STATE(88)] = 2738,
  [SMALL_STATE(89)] = 2754,
  [SMALL_STATE(90)] = 2770,
  [SMALL_STATE(91)] = 2786,
  [SMALL_STATE(92)] = 2802,
  [SMALL_STATE(93)] = 2818,
  [SMALL_STATE(94)] = 2834,
  [SMALL_STATE(95)] = 2848,
  [SMALL_STATE(96)] = 2864,
  [SMALL_STATE(97)] = 2880,
  [SMALL_STATE(98)] = 2892,
  [SMALL_STATE(99)] = 2903,
  [SMALL_STATE(100)] = 2916,
  [SMALL_STATE(101)] = 2926,
  [SMALL_STATE(102)] = 2936,
  [SMALL_STATE(103)] = 2946,
  [SMALL_STATE(104)] = 2956,
  [SMALL_STATE(105)] = 2966,
  [SMALL_STATE(106)] = 2976,
  [SMALL_STATE(107)] = 2986,
  [SMALL_STATE(108)] = 2990,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(105),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(64),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(30),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(55),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(29),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(29),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(74),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(81),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subset, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subset, 4),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_left_assignment, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_left_assignment, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(105),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(30),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(55),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(29),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(29),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(74),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(81),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 2),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(106),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(22),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(53),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(34),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(34),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(82),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(75),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 3),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(97),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(84),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2), SHIFT_REPEAT(99),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 1),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [294] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_R(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
