#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7

enum {
  anon_sym_function = 1,
  anon_sym_LPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_RPAREN = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_LT_DASH = 8,
  anon_sym_LT_LT_DASH = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  anon_sym_BANG = 14,
  anon_sym_STAR = 15,
  anon_sym_EQ_EQ = 16,
  anon_sym_PIPE = 17,
  anon_sym_AMP = 18,
  sym_identifier = 19,
  sym_integer = 20,
  anon_sym_POUND = 21,
  aux_sym_comment_token1 = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_token1 = 24,
  anon_sym_BSLASH = 25,
  anon_sym_SQUOTE = 26,
  aux_sym_string_token2 = 27,
  sym_program = 28,
  sym_function_definition = 29,
  sym__parameter = 30,
  sym_argument_list = 31,
  sym_call = 32,
  sym_left_assignment = 33,
  sym_brace_list = 34,
  sym_subset = 35,
  sym_unary = 36,
  sym_binary = 37,
  sym__expression = 38,
  sym_comment = 39,
  sym_string = 40,
  aux_sym_program_repeat1 = 41,
  aux_sym_function_definition_repeat1 = 42,
  aux_sym_argument_list_repeat1 = 43,
  aux_sym_string_repeat1 = 44,
  aux_sym_string_repeat2 = 45,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LT_LT_DASH] = "<<-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_program] = "program",
  [sym_function_definition] = "function_definition",
  [sym__parameter] = "_parameter",
  [sym_argument_list] = "argument_list",
  [sym_call] = "call",
  [sym_left_assignment] = "left_assignment",
  [sym_brace_list] = "brace_list",
  [sym_subset] = "subset",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym__expression] = "_expression",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LT_LT_DASH] = anon_sym_LT_LT_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_program] = sym_program,
  [sym_function_definition] = sym_function_definition,
  [sym__parameter] = sym__parameter,
  [sym_argument_list] = sym_argument_list,
  [sym_call] = sym_call,
  [sym_left_assignment] = sym_left_assignment,
  [sym_brace_list] = sym_brace_list,
  [sym_subset] = sym_subset,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym__expression] = sym__expression,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter] = {
    .visible = false,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_left_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_list] = {
    .visible = true,
    .named = true,
  },
  [sym_subset] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '&') ADVANCE(26);
      if (lookahead == '\'') ADVANCE(48);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(49);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_function);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_LT_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(9);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(29);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {(TSStateId)(-1)},
  [108] = {.lex_state = 39},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LT_LT_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(105),
    [sym_function_definition] = STATE(31),
    [sym_call] = STATE(31),
    [sym_left_assignment] = STATE(31),
    [sym_brace_list] = STATE(31),
    [sym_subset] = STATE(31),
    [sym_unary] = STATE(31),
    [sym_binary] = STATE(31),
    [sym__expression] = STATE(52),
    [sym_comment] = STATE(1),
    [sym_string] = STATE(31),
    [aux_sym_program_repeat1] = STATE(46),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_integer] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [anon_sym_function] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LT_DASH] = ACTIONS(23),
    [anon_sym_LT_LT_DASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_AMP] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [anon_sym_function] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_EQ] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LT_DASH] = ACTIONS(27),
    [anon_sym_LT_LT_DASH] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_AMP] = ACTIONS(27),
    [sym_identifier] = ACTIONS(25),
    [sym_integer] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(27),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [anon_sym_function] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_EQ] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LT_DASH] = ACTIONS(35),
    [anon_sym_LT_LT_DASH] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(35),
    [sym_identifier] = ACTIONS(33),
    [sym_integer] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(35),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [anon_sym_function] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_EQ] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LT_DASH] = ACTIONS(39),
    [anon_sym_LT_LT_DASH] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(39),
    [anon_sym_PIPE] = ACTIONS(39),
    [anon_sym_AMP] = ACTIONS(39),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(39),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(39),
  },
  [6] = {
    [sym_comment] = STATE(6),
    [anon_sym_function] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_EQ] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_LT_DASH] = ACTIONS(43),
    [anon_sym_LT_LT_DASH] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_AMP] = ACTIONS(43),
    [sym_identifier] = ACTIONS(41),
    [sym_integer] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(43),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [anon_sym_function] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_LT_DASH] = ACTIONS(47),
    [anon_sym_LT_LT_DASH] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(47),
    [anon_sym_RBRACK] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_AMP] = ACTIONS(47),
    [sym_identifier] = ACTIONS(45),
    [sym_integer] = ACTIONS(47),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [anon_sym_SQUOTE] = ACTIONS(47),
  },
  [8] = {
    [sym_comment] = STATE(8),
    [anon_sym_function] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_EQ] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LT_DASH] = ACTIONS(51),
    [anon_sym_LT_LT_DASH] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_RBRACK] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_AMP] = ACTIONS(51),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(51),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(51),
  },
  [9] = {
    [sym_comment] = STATE(9),
    [anon_sym_function] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LT_DASH] = ACTIONS(23),
    [anon_sym_LT_LT_DASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_AMP] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
  },
  [10] = {
    [sym_function_definition] = STATE(19),
    [sym_call] = STATE(19),
    [sym_left_assignment] = STATE(19),
    [sym_brace_list] = STATE(19),
    [sym_subset] = STATE(19),
    [sym_unary] = STATE(19),
    [sym_binary] = STATE(19),
    [sym__expression] = STATE(40),
    [sym_comment] = STATE(10),
    [sym_string] = STATE(19),
    [aux_sym_argument_list_repeat1] = STATE(21),
    [anon_sym_function] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [sym_integer] = ACTIONS(65),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(69),
  },
  [11] = {
    [sym_comment] = STATE(11),
    [anon_sym_function] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LT_DASH] = ACTIONS(23),
    [anon_sym_LT_LT_DASH] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_AMP] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
  },
  [12] = {
    [sym_comment] = STATE(12),
    [anon_sym_function] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_LT_DASH] = ACTIONS(79),
    [anon_sym_LT_LT_DASH] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_AMP] = ACTIONS(83),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(75),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(75),
    [anon_sym_SQUOTE] = ACTIONS(75),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [anon_sym_function] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(87),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_EQ] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(87),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_LT_DASH] = ACTIONS(87),
    [anon_sym_LT_LT_DASH] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(87),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(87),
    [anon_sym_BANG] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_EQ_EQ] = ACTIONS(87),
    [anon_sym_PIPE] = ACTIONS(87),
    [anon_sym_AMP] = ACTIONS(87),
    [sym_identifier] = ACTIONS(85),
    [sym_integer] = ACTIONS(87),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(87),
    [anon_sym_SQUOTE] = ACTIONS(87),
  },
  [14] = {
    [sym_comment] = STATE(14),
    [anon_sym_function] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(91),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_EQ] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_LT_DASH] = ACTIONS(91),
    [anon_sym_LT_LT_DASH] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(91),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_PLUS] = ACTIONS(91),
    [anon_sym_BANG] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(91),
    [anon_sym_EQ_EQ] = ACTIONS(91),
    [anon_sym_PIPE] = ACTIONS(91),
    [anon_sym_AMP] = ACTIONS(91),
    [sym_identifier] = ACTIONS(89),
    [sym_integer] = ACTIONS(91),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(91),
    [anon_sym_SQUOTE] = ACTIONS(91),
  },
  [15] = {
    [sym_comment] = STATE(15),
    [anon_sym_function] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(95),
    [anon_sym_EQ] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_LT_DASH] = ACTIONS(95),
    [anon_sym_LT_LT_DASH] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(95),
    [anon_sym_PLUS] = ACTIONS(95),
    [anon_sym_BANG] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(95),
    [anon_sym_EQ_EQ] = ACTIONS(95),
    [anon_sym_PIPE] = ACTIONS(95),
    [anon_sym_AMP] = ACTIONS(95),
    [sym_identifier] = ACTIONS(93),
    [sym_integer] = ACTIONS(95),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(95),
    [anon_sym_SQUOTE] = ACTIONS(95),
  },
  [16] = {
    [sym_comment] = STATE(16),
    [anon_sym_function] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(99),
    [anon_sym_COMMA] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(99),
    [anon_sym_EQ] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_LT_DASH] = ACTIONS(99),
    [anon_sym_LT_LT_DASH] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_RBRACK] = ACTIONS(99),
    [anon_sym_DASH] = ACTIONS(99),
    [anon_sym_PLUS] = ACTIONS(99),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(99),
    [anon_sym_EQ_EQ] = ACTIONS(99),
    [anon_sym_PIPE] = ACTIONS(99),
    [anon_sym_AMP] = ACTIONS(99),
    [sym_identifier] = ACTIONS(97),
    [sym_integer] = ACTIONS(99),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(99),
  },
  [17] = {
    [sym_comment] = STATE(17),
    [anon_sym_function] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_EQ] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_LT_DASH] = ACTIONS(103),
    [anon_sym_LT_LT_DASH] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(103),
    [anon_sym_PLUS] = ACTIONS(103),
    [anon_sym_BANG] = ACTIONS(103),
    [anon_sym_STAR] = ACTIONS(103),
    [anon_sym_EQ_EQ] = ACTIONS(103),
    [anon_sym_PIPE] = ACTIONS(103),
    [anon_sym_AMP] = ACTIONS(103),
    [sym_identifier] = ACTIONS(101),
    [sym_integer] = ACTIONS(103),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(103),
    [anon_sym_SQUOTE] = ACTIONS(103),
  },
  [18] = {
    [sym_comment] = STATE(18),
    [anon_sym_function] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(107),
    [anon_sym_RPAREN] = ACTIONS(107),
    [anon_sym_EQ] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_LT_DASH] = ACTIONS(107),
    [anon_sym_LT_LT_DASH] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(107),
    [anon_sym_RBRACK] = ACTIONS(107),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_PLUS] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(107),
    [anon_sym_STAR] = ACTIONS(107),
    [anon_sym_EQ_EQ] = ACTIONS(107),
    [anon_sym_PIPE] = ACTIONS(107),
    [anon_sym_AMP] = ACTIONS(107),
    [sym_identifier] = ACTIONS(105),
    [sym_integer] = ACTIONS(107),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(107),
    [anon_sym_SQUOTE] = ACTIONS(107),
  },
  [19] = {
    [sym_comment] = STATE(19),
    [anon_sym_function] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(111),
    [anon_sym_COMMA] = ACTIONS(111),
    [anon_sym_RPAREN] = ACTIONS(111),
    [anon_sym_EQ] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_LT_DASH] = ACTIONS(111),
    [anon_sym_LT_LT_DASH] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(111),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_PLUS] = ACTIONS(111),
    [anon_sym_BANG] = ACTIONS(111),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym_EQ_EQ] = ACTIONS(111),
    [anon_sym_PIPE] = ACTIONS(111),
    [anon_sym_AMP] = ACTIONS(111),
    [sym_identifier] = ACTIONS(109),
    [sym_integer] = ACTIONS(111),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(111),
    [anon_sym_SQUOTE] = ACTIONS(111),
  },
  [20] = {
    [sym_function_definition] = STATE(19),
    [sym_argument_list] = STATE(103),
    [sym_call] = STATE(19),
    [sym_left_assignment] = STATE(19),
    [sym_brace_list] = STATE(19),
    [sym_subset] = STATE(19),
    [sym_unary] = STATE(19),
    [sym_binary] = STATE(19),
    [sym__expression] = STATE(40),
    [sym_comment] = STATE(20),
    [sym_string] = STATE(19),
    [aux_sym_argument_list_repeat1] = STATE(10),
    [anon_sym_function] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [sym_integer] = ACTIONS(65),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(69),
  },
  [21] = {
    [sym_function_definition] = STATE(19),
    [sym_call] = STATE(19),
    [sym_left_assignment] = STATE(19),
    [sym_brace_list] = STATE(19),
    [sym_subset] = STATE(19),
    [sym_unary] = STATE(19),
    [sym_binary] = STATE(19),
    [sym__expression] = STATE(40),
    [sym_comment] = STATE(21),
    [sym_string] = STATE(19),
    [aux_sym_argument_list_repeat1] = STATE(21),
    [anon_sym_function] = ACTIONS(115),
    [anon_sym_COMMA] = ACTIONS(118),
    [anon_sym_RPAREN] = ACTIONS(121),
    [anon_sym_LBRACE] = ACTIONS(123),
    [anon_sym_RBRACK] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(126),
    [anon_sym_PLUS] = ACTIONS(126),
    [anon_sym_BANG] = ACTIONS(126),
    [sym_identifier] = ACTIONS(129),
    [sym_integer] = ACTIONS(132),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(135),
    [anon_sym_SQUOTE] = ACTIONS(138),
  },
  [22] = {
    [sym_function_definition] = STATE(19),
    [sym_argument_list] = STATE(100),
    [sym_call] = STATE(19),
    [sym_left_assignment] = STATE(19),
    [sym_brace_list] = STATE(19),
    [sym_subset] = STATE(19),
    [sym_unary] = STATE(19),
    [sym_binary] = STATE(19),
    [sym__expression] = STATE(40),
    [sym_comment] = STATE(22),
    [sym_string] = STATE(19),
    [aux_sym_argument_list_repeat1] = STATE(10),
    [anon_sym_function] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(141),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [sym_integer] = ACTIONS(65),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(69),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(41), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(43), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [32] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_comment,
    ACTIONS(85), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(87), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [64] = 14,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(10), 1,
      aux_sym_argument_list_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(40), 1,
      sym__expression,
    STATE(101), 1,
      sym_argument_list,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [116] = 14,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(10), 1,
      aux_sym_argument_list_repeat1,
    STATE(26), 1,
      sym_comment,
    STATE(40), 1,
      sym__expression,
    STATE(104), 1,
      sym_argument_list,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [168] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(33), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(35), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [204] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(45), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(47), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [236] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(147), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(83), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(121), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [282] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(27), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [318] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(111), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [350] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(97), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(99), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [382] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(33), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(95), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [414] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(34), 1,
      sym_comment,
    ACTIONS(89), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(91), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [446] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(49), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(51), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [482] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(107), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [514] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      anon_sym_function,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(163), 1,
      sym_integer,
    ACTIONS(166), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym__expression,
    STATE(37), 1,
      sym_comment,
    ACTIONS(152), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(157), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [562] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(37), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(39), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [598] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(21), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(23), 15,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [634] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    STATE(40), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(172), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(83), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(152), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [680] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(178), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(182), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(75), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [726] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(103), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [758] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(21), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(23), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [792] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    ACTIONS(21), 3,
      anon_sym_function,
      anon_sym_EQ,
      sym_identifier,
    ACTIONS(23), 18,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [824] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_program_repeat1,
    STATE(53), 1,
      sym__expression,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [873] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    STATE(46), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_program_repeat1,
    STATE(52), 1,
      sym__expression,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [922] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_function,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      sym_identifier,
    ACTIONS(202), 1,
      sym_integer,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(208), 1,
      anon_sym_SQUOTE,
    STATE(53), 1,
      sym__expression,
    STATE(47), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(196), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [969] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_program_repeat1,
    STATE(48), 1,
      sym_comment,
    STATE(53), 1,
      sym__expression,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1018] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
    ACTIONS(213), 1,
      anon_sym_function,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
    ACTIONS(222), 1,
      sym_identifier,
    ACTIONS(225), 1,
      sym_integer,
    ACTIONS(228), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    STATE(52), 1,
      sym__expression,
    STATE(49), 2,
      sym_comment,
      aux_sym_program_repeat1,
    ACTIONS(219), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1065] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_program_repeat1,
    STATE(53), 1,
      sym__expression,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1114] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      aux_sym_program_repeat1,
    STATE(51), 1,
      sym_comment,
    STATE(53), 1,
      sym__expression,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1163] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    STATE(52), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(178), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(240), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(182), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(238), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1207] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    STATE(53), 1,
      sym_comment,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(79), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(240), 2,
      anon_sym_function,
      sym_identifier,
    ACTIONS(83), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(238), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      sym_integer,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1251] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(4), 1,
      sym__expression,
    STATE(54), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1294] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(55), 1,
      sym_comment,
    STATE(73), 1,
      sym__expression,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1337] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      sym__expression,
    STATE(56), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1380] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(39), 1,
      sym__expression,
    STATE(57), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1423] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(17), 1,
      sym__expression,
    STATE(58), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1466] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(27), 1,
      sym__expression,
    STATE(59), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1509] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      sym__expression,
    STATE(60), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1552] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(3), 1,
      sym__expression,
    STATE(61), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1595] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(42), 1,
      sym__expression,
    STATE(62), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1638] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(30), 1,
      sym__expression,
    STATE(63), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1681] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(41), 1,
      sym__expression,
    STATE(64), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1724] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(5), 1,
      sym__expression,
    STATE(65), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1767] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(38), 1,
      sym__expression,
    STATE(66), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1810] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(8), 1,
      sym__expression,
    STATE(67), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1853] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(43), 1,
      sym__expression,
    STATE(68), 1,
      sym_comment,
    ACTIONS(11), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(31), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1896] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(12), 1,
      sym__expression,
    STATE(69), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1939] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(11), 1,
      sym__expression,
    STATE(70), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [1982] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(2), 1,
      sym__expression,
    STATE(71), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2025] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(53), 1,
      anon_sym_function,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_SQUOTE,
    STATE(9), 1,
      sym__expression,
    STATE(72), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 8,
      sym_function_definition,
      sym_call,
      sym_left_assignment,
      sym_brace_list,
      sym_subset,
      sym_unary,
      sym_binary,
      sym_string,
  [2068] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_STAR,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(180), 1,
      anon_sym_LBRACK,
    STATE(73), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(178), 2,
      anon_sym_LT_DASH,
      anon_sym_LT_LT_DASH,
    ACTIONS(242), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(182), 3,
      anon_sym_EQ_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
  [2104] = 4,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    ACTIONS(248), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
    STATE(74), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [2119] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      aux_sym_string_repeat1,
    STATE(75), 1,
      sym_comment,
    ACTIONS(253), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2136] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    STATE(76), 1,
      sym_comment,
    STATE(81), 1,
      aux_sym_string_repeat2,
    ACTIONS(255), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2153] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(257), 1,
      anon_sym_DQUOTE,
    STATE(74), 1,
      aux_sym_string_repeat1,
    STATE(77), 1,
      sym_comment,
    ACTIONS(253), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2170] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(251), 1,
      anon_sym_SQUOTE,
    STATE(78), 1,
      sym_comment,
    STATE(81), 1,
      aux_sym_string_repeat2,
    ACTIONS(255), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2187] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(259), 1,
      anon_sym_SQUOTE,
    STATE(76), 1,
      aux_sym_string_repeat2,
    STATE(79), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2204] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(259), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      aux_sym_string_repeat1,
    STATE(80), 1,
      sym_comment,
    ACTIONS(253), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2221] = 4,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(264), 1,
      anon_sym_SQUOTE,
    ACTIONS(261), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
    STATE(81), 2,
      sym_comment,
      aux_sym_string_repeat2,
  [2236] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(266), 1,
      anon_sym_SQUOTE,
    STATE(78), 1,
      aux_sym_string_repeat2,
    STATE(82), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_BSLASH,
      aux_sym_string_token2,
  [2253] = 5,
    ACTIONS(244), 1,
      anon_sym_POUND,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
    STATE(75), 1,
      aux_sym_string_repeat1,
    STATE(83), 1,
      sym_comment,
    ACTIONS(253), 2,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2270] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(270), 1,
      anon_sym_EQ,
    STATE(84), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2284] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(85), 1,
      sym_comment,
    STATE(88), 1,
      sym__parameter,
  [2300] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2316] = 3,
    ACTIONS(244), 1,
      anon_sym_POUND,
    STATE(87), 1,
      sym_comment,
    ACTIONS(278), 3,
      anon_sym_BSLASH,
      anon_sym_SQUOTE,
      aux_sym_string_token2,
  [2328] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_comment,
    STATE(97), 1,
      aux_sym_function_definition_repeat1,
  [2344] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_comment,
    STATE(90), 1,
      aux_sym_function_definition_repeat1,
  [2360] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(90), 2,
      sym_comment,
      aux_sym_function_definition_repeat1,
  [2374] = 3,
    ACTIONS(244), 1,
      anon_sym_POUND,
    STATE(91), 1,
      sym_comment,
    ACTIONS(293), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [2386] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2402] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2418] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_comment,
    STATE(98), 1,
      sym__parameter,
  [2434] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_function_definition_repeat1,
    STATE(95), 1,
      sym_comment,
  [2450] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym__parameter,
    STATE(96), 1,
      sym_comment,
  [2466] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_function_definition_repeat1,
    STATE(97), 1,
      sym_comment,
  [2482] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(98), 1,
      sym_comment,
    ACTIONS(291), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2493] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(98), 1,
      sym__parameter,
    STATE(99), 1,
      sym_comment,
  [2506] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(100), 1,
      sym_comment,
  [2516] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(309), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      sym_comment,
  [2526] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(311), 1,
      anon_sym_LPAREN,
    STATE(102), 1,
      sym_comment,
  [2536] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      sym_comment,
  [2546] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(315), 1,
      anon_sym_RBRACK,
    STATE(104), 1,
      sym_comment,
  [2556] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(317), 1,
      ts_builtin_sym_end,
    STATE(105), 1,
      sym_comment,
  [2566] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(319), 1,
      anon_sym_LPAREN,
    STATE(106), 1,
      sym_comment,
  [2576] = 1,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
  [2580] = 1,
    ACTIONS(323), 1,
      aux_sym_comment_token1,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 32,
  [SMALL_STATE(25)] = 64,
  [SMALL_STATE(26)] = 116,
  [SMALL_STATE(27)] = 168,
  [SMALL_STATE(28)] = 204,
  [SMALL_STATE(29)] = 236,
  [SMALL_STATE(30)] = 282,
  [SMALL_STATE(31)] = 318,
  [SMALL_STATE(32)] = 350,
  [SMALL_STATE(33)] = 382,
  [SMALL_STATE(34)] = 414,
  [SMALL_STATE(35)] = 446,
  [SMALL_STATE(36)] = 482,
  [SMALL_STATE(37)] = 514,
  [SMALL_STATE(38)] = 562,
  [SMALL_STATE(39)] = 598,
  [SMALL_STATE(40)] = 634,
  [SMALL_STATE(41)] = 680,
  [SMALL_STATE(42)] = 726,
  [SMALL_STATE(43)] = 758,
  [SMALL_STATE(44)] = 792,
  [SMALL_STATE(45)] = 824,
  [SMALL_STATE(46)] = 873,
  [SMALL_STATE(47)] = 922,
  [SMALL_STATE(48)] = 969,
  [SMALL_STATE(49)] = 1018,
  [SMALL_STATE(50)] = 1065,
  [SMALL_STATE(51)] = 1114,
  [SMALL_STATE(52)] = 1163,
  [SMALL_STATE(53)] = 1207,
  [SMALL_STATE(54)] = 1251,
  [SMALL_STATE(55)] = 1294,
  [SMALL_STATE(56)] = 1337,
  [SMALL_STATE(57)] = 1380,
  [SMALL_STATE(58)] = 1423,
  [SMALL_STATE(59)] = 1466,
  [SMALL_STATE(60)] = 1509,
  [SMALL_STATE(61)] = 1552,
  [SMALL_STATE(62)] = 1595,
  [SMALL_STATE(63)] = 1638,
  [SMALL_STATE(64)] = 1681,
  [SMALL_STATE(65)] = 1724,
  [SMALL_STATE(66)] = 1767,
  [SMALL_STATE(67)] = 1810,
  [SMALL_STATE(68)] = 1853,
  [SMALL_STATE(69)] = 1896,
  [SMALL_STATE(70)] = 1939,
  [SMALL_STATE(71)] = 1982,
  [SMALL_STATE(72)] = 2025,
  [SMALL_STATE(73)] = 2068,
  [SMALL_STATE(74)] = 2104,
  [SMALL_STATE(75)] = 2119,
  [SMALL_STATE(76)] = 2136,
  [SMALL_STATE(77)] = 2153,
  [SMALL_STATE(78)] = 2170,
  [SMALL_STATE(79)] = 2187,
  [SMALL_STATE(80)] = 2204,
  [SMALL_STATE(81)] = 2221,
  [SMALL_STATE(82)] = 2236,
  [SMALL_STATE(83)] = 2253,
  [SMALL_STATE(84)] = 2270,
  [SMALL_STATE(85)] = 2284,
  [SMALL_STATE(86)] = 2300,
  [SMALL_STATE(87)] = 2316,
  [SMALL_STATE(88)] = 2328,
  [SMALL_STATE(89)] = 2344,
  [SMALL_STATE(90)] = 2360,
  [SMALL_STATE(91)] = 2374,
  [SMALL_STATE(92)] = 2386,
  [SMALL_STATE(93)] = 2402,
  [SMALL_STATE(94)] = 2418,
  [SMALL_STATE(95)] = 2434,
  [SMALL_STATE(96)] = 2450,
  [SMALL_STATE(97)] = 2466,
  [SMALL_STATE(98)] = 2482,
  [SMALL_STATE(99)] = 2493,
  [SMALL_STATE(100)] = 2506,
  [SMALL_STATE(101)] = 2516,
  [SMALL_STATE(102)] = 2526,
  [SMALL_STATE(103)] = 2536,
  [SMALL_STATE(104)] = 2546,
  [SMALL_STATE(105)] = 2556,
  [SMALL_STATE(106)] = 2566,
  [SMALL_STATE(107)] = 2576,
  [SMALL_STATE(108)] = 2580,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subset, 4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subset, 4),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_left_assignment, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_left_assignment, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(106),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(37),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(50),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(58),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(19),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(19),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(80),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(79),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(106),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(50),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(58),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(19),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(19),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(80),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 1), SHIFT_REPEAT(79),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(106),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(50),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(58),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(19),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(19),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(80),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(79),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(102),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(48),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(62),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(31),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(31),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(83),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(82),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [248] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(91),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(87),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 1),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 1),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2), SHIFT_REPEAT(99),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [317] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_R(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
