[package]
name = "tree-sitter-tsx"
description = "Tsx grammar for the tree-sitter parsing library"
version = "0.16.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tsx"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-tsx"
edition = "2018"

build = "src/build.rs"
include = [
  "./*",
  "../../../tsx/grammar.js",
  "../../../queries/*",
  "../../../tsx/src/*",
]

[lib]
path = "src/lib.rs"

[dependencies]
tree-sitter = "0.17"

[build-dependencies]
cc = "1.0"
