name: Publish `grammar.json` and `parser.c`

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run test-ci
    - name: Publish parser source
      uses: actions/upload-artifact@v2
      with:
        name: generated-parser-src
        path: src
