name: Playground

on:
  push:
    branches:
      - main

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npx tree-sitter build-wasm
      - run: mv tree-sitter-elm.wasm docs/js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update playground
