name: Publish prebuilds

on:
  release:
    types: [created]

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: |
          npm i
      - run: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
        env:
          PREBUILD_UPLOAD: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
