name: Test full Linux

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: |
          npm i
      - name: Unit tests
        run: |
          npx tree-sitter test
      - name: Test examples
        continue-on-error: true
        run: |
          script/parse-examples-full
